CREATE TABLE pessoa(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(2000),
cpf VARCHAR(2000)
);
CREATE TABLE usuario(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(255),
senha VARCHAR(255)
);
CREATE TABLE album(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(2000),
genero VARCHAR(2000),
banda VARCHAR(2000)
);
CREATE TABLE equipe(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255),
modalidade VARCHAR(255),
torcedores INT
);
